### ISSUE TITLE
 The scope of a local variable

### ISSUE THREAD

**Issue by czlc** [WheretIB/LuaDkmDebugger#16]
local i = 1
 do
    local i = 3
    print(i)  --  debugger show i is 1
end

**Comment by WheretIB** [comment]
Fix for issue has been implemented, when inner 'i' comes into scope it will 'shadow' the outer 'i'.
This will be included in the next release.

Note: hover will display '3' when hovering over both variables while on the print statement because inner local shadows the outer one and the value evaluation doesn't support the location of the mouse.
Visual Studio 'Locals' panel can be used to see both variables.

**Comment by WheretIB** [comment]
Fixed in 852d72ae8b3d63002a855f0af607c94f36412442
Released in https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.9
